"""Generate the sample puzzles + live clues, emit site/puzzles.json.

Each spec reproduces a real grid from the puzzledesk engines (pinned seeds/params, so
the *grids* are deterministic) and clues it through the live Claude adapter. The output
feeds the static HTML player (see render_pages.py). Clue text is the one non-deterministic
part -- it is generated fresh by the model each run, so re-running produces the same grids
with new clues.

Run from the repo root, with the clue extra and a key (see Config.clue_api_key_env, D17)::

    uv run --extra clue python site/generate_puzzles.py     # -> site/puzzles.json
    uv run python site/render_pages.py                      # -> site/*.html + index.html
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

from puzzledesk.adapters.claude_clue import ClaudeClueProvider
from puzzledesk.app.clue import ClueStyle, Difficulty
from puzzledesk.app.cluing import ClueService
from puzzledesk.app.puzzle import FilledGrid, filled_from_blocked
from puzzledesk.bootstrap import Config, build
from puzzledesk.core.engines import gibbs_layout, patterns

OUT = sys.argv[1] if len(sys.argv) > 1 else str(pathlib.Path(__file__).parent / "puzzles.json")

c = build()
key = os.environ.get(Config.default().clue_api_key_env or "ANTHROPIC_API_KEY_TWO")
provider = ClaudeClueProvider(model="claude-opus-4-8", max_tokens=8192, api_key=key)
cluer = ClueService(provider, candidates=2)


def square_mini() -> FilledGrid:
    b = c.mini.generate(n=5, min_score=90, count=6)
    r = next(r for r in b.results if r.across[0].word == "scare")
    return FilledGrid(tuple(tuple(ch for ch in a.word) for a in r.across))


def blocked_mini() -> FilledGrid:
    fg = c.blocked.fill_grid_once(5, 5, 4, min_score=72, seed=2, symmetric=True)
    assert fg is not None
    return fg


def midi_capped() -> FilledGrid:
    mlex = c.lexicon.load_multi("cw", range(3, 6), min_score=66)
    found = patterns.fill_capped(
        10, 10, mlex, rng_factory=c.rng_factory, max_len=5, seed=3, min_len=3,
        symmetric=True, distinct=True, max_black=24, layout_node_budget=300_000,
    )
    assert found is not None
    return filled_from_blocked(*found)


def field_gibbs() -> FilledGrid:
    mlex = c.lexicon.load_multi("cw", range(3, 6), min_score=63)
    found = gibbs_layout.fill_gibbs(
        10, 10, mlex, rng_factory=c.rng_factory, max_len=5, seed=4, min_len=3,
        symmetric=True, distinct=True, black_fraction=0.17, target_black=None, max_layouts=40,
    )
    assert found is not None
    return filled_from_blocked(*found)


SPECS = [
    dict(id="mini", title="The Mini", tag="Double word square",
         difficulty=Difficulty.MONDAY, build=square_mini,
         blurb="A 5×5 with no black cells — every letter checked twice. Five across "
               "words and five down words, fully interlocked: a double word square.",
         note="Generated by the complete backtracking search over a quality-filtered "
              "lexicon (mini 5 90). Every one of the ten words scores ≥ 90 on the "
              "curated crossword list, and all ten are distinct — no symmetric-square "
              "cheat.",
         make="uv run mini 5 90 1"),
    dict(id="blocked", title="The Blocked Mini", tag="Black cells from a count",
         difficulty=Difficulty.TUESDAY, build=blocked_mini,
         blurb="A 5×5 with four black cells. The layout was not drawn by hand — you "
               "give the generator a black-cell count and it searches the legal grids.",
         note="The four blacks are a rotation-symmetric, fully-checked, connected layout "
              "found by complete search from the number 4 alone (generate 5 5 4). "
              "The fill then solves that layout above the bar — both stages complete, so "
              "“no grid” would be a theorem, not a timeout.",
         make="uv run generate 5 5 4 72 1"),
    dict(id="midi", title="The Midi", tag="Length-capped 10×10",
         difficulty=Difficulty.WEDNESDAY, build=midi_capped,
         blurb="A 10×10 built entirely from words of length 3–5. Black cells are placed "
               "to hold every entry short, so a big grid fills from a small word list.",
         note="The layout comes from the cap-driven search: fix the *maximum* entry "
              "length (here 5) and let tactically placed blacks keep every run in range. "
              "That is what lets a 10×10 fill from the same 2–5-letter lists a mini uses "
              "— no ten-letter word lists needed (generate 10 10 0 66 1 --max-len 5).",
         make="uv run generate 10 10 0 66 1 --max-len 5"),
    dict(id="field", title="The Field", tag="Gibbs-sampled layout",
         difficulty=Difficulty.THURSDAY, build=field_gibbs,
         blurb="Another 10×10 — but this one’s black-cell pattern was *sampled* from an "
               "energy field, not searched. Spread-out blacks, and never a 2×2 block.",
         note="The black-cell layout is drawn by an annealed-Gibbs sampler over the grid "
              "field, with the crossword aesthetics written as energy terms: a density "
              "spring, an anti-cluster penalty, and an explicit no-2×2-black-block rule "
              "it is guaranteed to satisfy. The complete search wins on speed; the field "
              "wins on texture (generate 10 10 0 63 1 --max-len 5 --gibbs).",
         make="uv run generate 10 10 0 63 1 --max-len 5 --gibbs"),
]


def export(spec) -> dict:
    grid: FilledGrid = spec["build"]()
    numbering = grid.numbering()
    style = ClueStyle(difficulty=spec["difficulty"])
    clued = cluer.clue(grid, style=style)

    def entries(kind):
        ts = sorted((t for t in grid.runs() if t.kind == kind),
                    key=lambda t: numbering[t.cells[0]])
        out = []
        for t in ts:
            cl = clued.clues.get(t.id)
            out.append(dict(
                num=numbering[t.cells[0]],
                clue=cl.text if cl is not None else "",
                answer=t.answer.upper(),
                len=len(t.cells),
                cells=[[r, col] for (r, col) in t.cells],
            ))
        return out

    cells = [[None if x is None else x.upper() for x in row] for row in grid.cells]
    black = sum(1 for row in cells for x in row if x is None)
    runs = grid.runs()
    sys.stderr.write(f"[{spec['id']}] clued, unclued={len(clued.unclued)}\n")
    return dict(
        id=spec["id"], title=spec["title"], tag=spec["tag"],
        difficulty=spec["difficulty"].name.title(), blurb=spec["blurb"],
        note=spec["note"], make=spec["make"],
        rows=grid.rows, cols=grid.cols, cells=cells,
        numbering={f"{r},{col}": n for (r, col), n in numbering.items()},
        across=entries("A"), down=entries("D"),
        stats=dict(entries=len(runs), black=black),
    )


puzzles = [export(s) for s in SPECS]
with open(OUT, "w") as f:
    json.dump(puzzles, f, indent=1, ensure_ascii=False)
sys.stderr.write(f"wrote {OUT} ({len(puzzles)} puzzles)\n")
