"""Generate the sample puzzles + live clues, emit site/puzzles.json.

Each spec reproduces a real grid from the puzzledesk engines (pinned seeds/params, so
the *grids* are deterministic) and clues it through the live Claude adapter. The output
feeds the static HTML player (see render_pages.py). Clue text is the one non-deterministic
part -- it is generated fresh by the model each run, so re-running produces the same grids
with new clues.

Run from the repo root, with the clue extra and a key (see Config.clue_api_key_env, D17)::

    uv run --extra clue python site/generate_puzzles.py     # -> site/puzzles.json
    uv run python site/render_pages.py                      # -> site/*.html + index.html
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

from puzzledesk.adapters.claude_clue import ClaudeClueProvider
from puzzledesk.app.clue import ClueStyle, Difficulty
from puzzledesk.app.cluing import ClueService
from puzzledesk.app.puzzle import FilledGrid, filled_from_blocked
from puzzledesk.bootstrap import Config, build
from puzzledesk.core.engines import gibbs_layout, patterns

DEFAULT_OUT = str(pathlib.Path(__file__).parent / "puzzles.json")

c = build()
key = os.environ.get(Config.default().clue_api_key_env or "ANTHROPIC_API_KEY_TWO")
provider = ClaudeClueProvider(model="claude-opus-4-8", max_tokens=8192, api_key=key)
cluer = ClueService(provider, candidates=2)


def square_mini() -> FilledGrid:
    b = c.mini.generate(n=5, min_score=90, count=6)
    r = next(r for r in b.results if r.across[0].word == "scare")
    return FilledGrid(tuple(tuple(ch for ch in a.word) for a in r.across))


def blocked_mini() -> FilledGrid:
    fg = c.blocked.fill_grid_once(5, 5, 4, min_score=72, seed=2, symmetric=True)
    assert fg is not None
    return fg


def blocked_mini_asym() -> FilledGrid:
    fg = c.blocked.fill_grid_once(5, 5, 4, min_score=72, seed=0, symmetric=False)
    assert fg is not None
    return fg


def midi_capped() -> FilledGrid:
    mlex = c.lexicon.load_multi("cw", range(3, 6), min_score=66)
    found = patterns.fill_capped(
        10, 10, mlex, rng_factory=c.rng_factory, max_len=5, seed=3, min_len=3,
        symmetric=True, distinct=True, max_black=24, layout_node_budget=300_000,
    )
    assert found is not None
    return filled_from_blocked(*found)


def midi_capped_asym() -> FilledGrid:
    mlex = c.lexicon.load_multi("cw", range(3, 6), min_score=66)
    found = patterns.fill_capped(
        10, 10, mlex, rng_factory=c.rng_factory, max_len=5, seed=0, min_len=3,
        symmetric=False, distinct=True, max_black=24, layout_node_budget=300_000,
    )
    assert found is not None
    return filled_from_blocked(*found)


def field_gibbs() -> FilledGrid:
    mlex = c.lexicon.load_multi("cw", range(3, 6), min_score=63)
    found = gibbs_layout.fill_gibbs(
        10, 10, mlex, rng_factory=c.rng_factory, max_len=5, seed=4, min_len=3,
        symmetric=True, distinct=True, black_fraction=0.17, target_black=None, max_layouts=40,
    )
    assert found is not None
    return filled_from_blocked(*found)


def midi_long_asym() -> FilledGrid:
    # A 9x9 with the length cap lifted to 6, so entries run longer than the mini's
    # five (RENDER, APIARY, VENEER, GRATES) -- length is a vocabulary axis (the 2..15
    # lists, D36), not the square-order axis. Layout is the asymmetric Gibbs field, so
    # the black cells fall freeform with a guaranteed no-2x2-block texture.
    mlex = c.lexicon.load_multi("cw", range(3, 7), min_score=60)
    found = gibbs_layout.fill_gibbs(
        9, 9, mlex, rng_factory=c.rng_factory, max_len=6, seed=9, min_len=3,
        symmetric=False, distinct=True, black_fraction=0.16, target_black=None, max_layouts=60,
    )
    assert found is not None
    return filled_from_blocked(*found)


SPECS = [
    dict(id="mini", title="The Mini", tag="Double word square",
         difficulty=Difficulty.MONDAY, build=square_mini,
         blurb="A 5×5 with no black cells — every letter checked twice. Five across "
               "words and five down words, fully interlocked: a double word square.",
         note="Generated by the complete backtracking search over a quality-filtered "
              "lexicon (mini 5 90). Every one of the ten words scores ≥ 90 on the "
              "curated crossword list, and all ten are distinct — no symmetric-square "
              "cheat.",
         make="uv run mini 5 90 1"),
    dict(id="blocked", title="The Blocked Mini", tag="Black cells from a count",
         difficulty=Difficulty.TUESDAY, build=blocked_mini,
         blurb="A 5×5 with four black cells. The layout was not drawn by hand — you "
               "give the generator a black-cell count and it searches the legal grids.",
         note="The four blacks are a rotation-symmetric, fully-checked, connected layout "
              "found by complete search from the number 4 alone (generate 5 5 4). "
              "The fill then solves that layout above the bar — both stages complete, so "
              "“no grid” would be a theorem, not a timeout.",
         make="uv run generate 5 5 4 72 1"),
    dict(id="blocked-asym", title="The Freeform Mini", tag="Asymmetric black cells",
         difficulty=Difficulty.TUESDAY, build=blocked_mini_asym,
         blurb="The same 5×5, four-black search as *The Blocked Mini* — but with the 180° "
               "symmetry requirement switched off. The blacks fall where the grid wants "
               "them, not in mirrored pairs, and the whole layout tilts.",
         note="The same count-driven complete search as its neighbour, with one constraint "
              "lifted: pass *--nonsymmetric* and the layout is no longer restricted to "
              "180°-rotation orbits, so the four blacks land wherever a legal, connected, "
              "fully-checked grid allows. Symmetry was always a default-on toggle here, not "
              "a hardwired rule (D13). The search stays complete and the fill still solves "
              "it above the bar, every entry distinct — only the mirror is gone.",
         make="uv run generate 5 5 4 72 1 --nonsymmetric"),
    dict(id="midi", title="The Midi", tag="Length-capped 10×10",
         difficulty=Difficulty.WEDNESDAY, build=midi_capped,
         blurb="A 10×10 built entirely from words of length 3–5. Black cells are placed "
               "to hold every entry short, so a big grid fills from a small word list.",
         note="The layout comes from the cap-driven search: fix the *maximum* entry "
              "length (here 5) and let tactically placed blacks keep every run in range. "
              "That is what lets a 10×10 fill from the same 2–5-letter lists a mini uses "
              "— no ten-letter word lists needed (generate 10 10 0 66 1 --max-len 5).",
         make="uv run generate 10 10 0 66 1 --max-len 5"),
    dict(id="midi-asym", title="The Freeform Midi", tag="Asymmetric 10×10",
         difficulty=Difficulty.WEDNESDAY, build=midi_capped_asym,
         blurb="The length-capped 10×10 again, symmetry off. Without the mirror constraint "
               "the black cells drift into a lopsided, freeform arrangement — the older, "
               "less formal crossword look, and a noticeably different feel to solve.",
         note="Identical to *The Midi* — cap-driven search, every entry 3–5 letters, layout "
              "from the number alone — except the 180° constraint is dropped "
              "(*--nonsymmetric*). Turning symmetry off widens the layout search from "
              "rotation orbits to every cell independently; the same completeness and "
              "distinctness guarantees hold, so this is the identical machine with one "
              "aesthetic rule removed, not a weaker one.",
         make="uv run generate 10 10 0 66 1 --max-len 5 --nonsymmetric"),
    dict(id="field", title="The Field", tag="Gibbs-sampled layout",
         difficulty=Difficulty.THURSDAY, build=field_gibbs,
         blurb="Another 10×10 — but this one’s black-cell pattern was *sampled* from an "
               "energy field, not searched. Spread-out blacks, and never a 2×2 block.",
         note="The black-cell layout is drawn by an annealed-Gibbs sampler over the grid "
              "field, with the crossword aesthetics written as energy terms: a density "
              "spring, an anti-cluster penalty, and an explicit no-2×2-black-block rule "
              "it is guaranteed to satisfy. The complete search wins on speed; the field "
              "wins on texture (generate 10 10 0 63 1 --max-len 5 --gibbs).",
         make="uv run generate 10 10 0 63 1 --max-len 5 --gibbs"),
    dict(id="midi-long", title="The Long Midi", tag="Entries past five, asymmetric",
         difficulty=Difficulty.THURSDAY, build=midi_long_asym,
         blurb="A 9×9 whose length cap is lifted from the mini’s five to *six*, so several "
               "entries — RENDER, APIARY, VENEER, GRATES — run longer than any word a Mini "
               "can hold. The layout is a freeform, asymmetric one, sampled from the field.",
         note="Two independent levers. The *cap* is raised to 6, which lets longer entries "
              "in — and that costs nothing but vocabulary: the word lists run to length 15 "
              "(D36), so “how long a word can we hold” is a data axis, wholly separate from "
              "the double-square *order* that governs a dense mini. The *layout* is drawn by "
              "the same annealed-Gibbs field as *The Field*, but with 180° symmetry switched "
              "off, so the black cells fall freeform while still guaranteeing no 2×2 block. "
              "A bigger, more open grid built from slightly longer words, laid out asymmetrically.",
         make="uv run generate 9 9 0 60 1 --max-len 6 --gibbs --nonsymmetric"),
]


def export(spec) -> dict:
    grid: FilledGrid = spec["build"]()
    numbering = grid.numbering()
    style = ClueStyle(difficulty=spec["difficulty"])
    clued = cluer.clue(grid, style=style)

    def entries(kind):
        ts = sorted((t for t in grid.runs() if t.kind == kind),
                    key=lambda t: numbering[t.cells[0]])
        out = []
        for t in ts:
            cl = clued.clues.get(t.id)
            out.append(dict(
                num=numbering[t.cells[0]],
                clue=cl.text if cl is not None else "",
                answer=t.answer.upper(),
                len=len(t.cells),
                cells=[[r, col] for (r, col) in t.cells],
            ))
        return out

    cells = [[None if x is None else x.upper() for x in row] for row in grid.cells]
    black = sum(1 for row in cells for x in row if x is None)
    runs = grid.runs()
    sys.stderr.write(f"[{spec['id']}] clued, unclued={len(clued.unclued)}\n")
    return dict(
        id=spec["id"], title=spec["title"], tag=spec["tag"],
        difficulty=spec["difficulty"].name.title(), blurb=spec["blurb"],
        note=spec["note"], make=spec["make"],
        rows=grid.rows, cols=grid.cols, cells=cells,
        numbering={f"{r},{col}": n for (r, col), n in numbering.items()},
        across=entries("A"), down=entries("D"),
        stats=dict(entries=len(runs), black=black),
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("out", nargs="?", default=DEFAULT_OUT, help="output path (default: site/puzzles.json)")
    ap.add_argument(
        "--only",
        metavar="ID,ID",
        help="regenerate only these spec ids and merge them into the existing file, keeping "
             "every other puzzle's committed clues untouched (order always follows SPECS)",
    )
    args = ap.parse_args()

    ids = [s["id"] for s in SPECS]
    if args.only:
        wanted = [i.strip() for i in args.only.split(",") if i.strip()]
        unknown = [i for i in wanted if i not in ids]
        if unknown:
            ap.error(f"unknown spec id(s): {', '.join(unknown)} (known: {', '.join(ids)})")
        specs = [s for s in SPECS if s["id"] in wanted]
    else:
        specs = SPECS

    fresh = {s["id"]: export(s) for s in specs}

    out = pathlib.Path(args.out)
    kept: dict[str, dict] = {}
    if args.only and out.exists():
        kept = {p["id"]: p for p in json.loads(out.read_text())}

    puzzles = [fresh.get(s["id"], kept.get(s["id"])) for s in SPECS]
    puzzles = [p for p in puzzles if p is not None]
    out.write_text(json.dumps(puzzles, indent=1, ensure_ascii=False))
    sys.stderr.write(f"wrote {out} ({len(puzzles)} puzzles)\n")


if __name__ == "__main__":
    main()
